### ISSUE TITLE
Actividad  7

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-7-diagrama-de-clases-modelo-blockchain-tim-mlnce#1]
[actividad 7.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-diagrama-de-clases-modelo-blockchain-tim-mlnce/files/11594265/actividad.7.pdf)

**Comment by josealfredo79** [comment]
Calificacion

**Comment by MLR062998** [comment]
calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
